/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'albert' at '5/09/17 19:05' with Gradle 2.13
 *
 * @author albert, @date 5/09/17 19:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
